### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by timholy** [davidanthoff/ProfileVega.jl#21]
https://discourse.julialang.org/t/saving-profile-data/51173 led me to this:

```julia
julia> using RegistryCompatTools

julia> held_back_by("FlameGraphs")
2-element Vector{String}:
 "ProfileSVG"
 "ProfileVega"
```

**Comment by jgreener64** [comment]
Running into this too, any chance of a release?

**Comment by davidanthoff** [comment]
I just tagged a new release: https://github.com/JuliaRegistries/General/pull/35969. Sorry it took so long.

**Comment by jgreener64** [comment]
Thanks!
